server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:./testdb
    url: jdbc:h2:file:./testdb;AUTO_SERVER=TRUE
#    url: jdbc:p6spy:h2:file:./testdb;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

#logging:
#  level:
#    org.hibernate.sql: debug
#    com.p6spy.engine.spy.P6SpyDriver: debug
#    com.p6spy.engine.logging.P6LogFactory: debug
#    com.p6spy.engine.logging.P6LogStatement: info
#    org.hibernate.orm.jdbc.bind: trace
#    p6spy: debug

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

#p6spy:
#  config:
#    appender: com.p6spy.engine.spy.appender.Slf4JLogger
#    logMessageFormat: com.p6spy.engine.spy.appender.MultiLineFormat
#    logfile: spy.log
