server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:./testdb
    url: jdbc:h2:file:./testdb;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  level:
    org.hibernate.sql: debug

